### ISSUE TITLE
能制作一个linux-armhf的docker镜像吗？

### ISSUE THREAD

**Issue by aaasoft** [frank-lam/lanproxy-nat#1]
非常感谢你编写的详细文档和制作的docker镜像。目前我使用起来非常方便。目前的docker镜像只有linux-x64的，能不能制作一个linux-armhf的镜像呢，毕竟现在树莓派这么普及，很多人使用树莓派做服务器的，非常感谢！

**Comment by frank-lam** [comment]
@aaasoft 收到你的issue了。后续会考虑扩展docker镜像，但是目前对linux-armhf环境不是特别了解呢，最近工作比较忙碌，只能在业余时间尝试。如果你有兴趣并且有时间，也可以加入本仓库一起维护哈~

**Comment by aaasoft** [comment]
我也是这周的工作比较忙，暂时没有时间弄哈。我家里有一个树莓派，下周的时候我尝试制作一个linux-armhf的docker镜像哈。

**Comment by aaasoft** [comment]
我已经在树莓派上制作了一个armhf镜像了，可以在树莓派上正常工作。

镜像地址：https://hub.docker.com/r/aaasoft/lanproxy-client
Dockerfile：https://github.com/aaasoft/docker-lanproxy-client-armhf
